/* Reconciles the normalized curriculum LISTING (base vs final) into
 * portal/data/curriculum.js source edits.
 *
 * Strategy: move/patch EXISTING AST nodes wherever possible (moves carry
 * their attached comments with them); build fresh nodes only for genuinely
 * new entries. Untouched sections/items print byte-identically.
 *
 * Sections whose items are generated by code (s6/s7 use Array.from) are
 * left completely alone unless their items actually changed — in which case
 * the generator expression is materialized into an explicit array literal
 * (an honest, reviewable structural change that the git diff will show).
 */
import { parse, print, b, findExportConst, findTopLevelConst, objProp, objPropValue, setObjProp, staticString, valueToNode, deepEqual } from '../ast-utils.mjs';

function itemCallNode(item) {
  const args = [b.stringLiteral(item.id), b.stringLiteral(item.sectionId), b.stringLiteral(item.number)];
  if (item.form === 'real') {
    if (item.overrides && Object.keys(item.overrides).length) args.push(valueToNode(item.overrides));
    return b.callExpression(b.identifier('real'), args);
  }
  if (item.form === 'demo') return b.callExpression(b.identifier('demo'), args);
  args.push(b.stringLiteral(item.title || item.id));
  if (item.note) args.push(b.stringLiteral(item.note));
  return b.callExpression(b.identifier('placeholder'), args);
}

/** Patch an existing real()/demo()/placeholder() call in place. Returns the
 * node, or null if the item's FORM changed (caller builds a fresh call). */
function patchItemCall(node, item, sectionId) {
  if (node.type !== 'CallExpression' || node.callee.type !== 'Identifier') return null;
  const fn = node.callee.name;
  const expectForm = item.form === 'real' ? 'real' : item.form === 'demo' ? 'demo' : 'placeholder';
  if (fn !== expectForm) return null;
  const setStrArg = (i, val) => {
    if (staticString(node.arguments[i]) !== val) node.arguments[i] = b.stringLiteral(val);
  };
  setStrArg(1, sectionId);
  setStrArg(2, item.number);
  if (fn === 'real') {
    const hasOverrides = item.overrides && Object.keys(item.overrides).length;
    if (hasOverrides) node.arguments[3] = valueToNode(item.overrides);
    else if (node.arguments.length > 3) node.arguments.length = 3;
  } else if (fn === 'placeholder') {
    setStrArg(3, item.title || item.id);
    if (item.note) {
      if (staticString(node.arguments[4]) !== item.note) node.arguments[4] = b.stringLiteral(item.note);
    } else if (node.arguments.length > 4) node.arguments.length = 4;
  }
  return node;
}

function sectionNode(section, itemsExpr) {
  const props = {
    id: section.id, number: section.number, title: section.title,
    type: section.type, icon: section.icon,
  };
  if (section.levelLabel) props.levelLabel = section.levelLabel;
  props.description = section.description || '';
  const obj = valueToNode(props);
  obj.properties.push(b.objectProperty(b.identifier('items'), itemsExpr));
  return obj;
}

export function writeCurriculum(source, baseModel, finalModel) {
  const base = baseModel.curriculum;
  const final = finalModel.curriculum;
  if (deepEqual(base, final)) return source;

  const ast = parse(source);
  const curriculumExpr = findExportConst(ast, 'CURRICULUM');
  const sectionsArr = objPropValue(curriculumExpr, 'sections');

  /* Index existing section nodes and their item arrays. */
  const sectionNodes = new Map(); // id -> section object node
  const itemArrays = new Map();   // section id -> { arr: ArrayExpression | null, generated: bool }
  const itemNodes = new Map();    // item id -> call node
  for (const el of sectionsArr.elements) {
    const id = staticString(objPropValue(el, 'id'));
    sectionNodes.set(id, el);
    const itemsVal = objPropValue(el, 'items');
    let arr = null;
    if (itemsVal.type === 'Identifier') arr = findTopLevelConst(ast, itemsVal.name);
    else if (itemsVal.type === 'ArrayExpression') arr = itemsVal;
    const generated = !arr || arr.type !== 'ArrayExpression';
    itemArrays.set(id, { arr: generated ? null : arr, generated, itemsVal, node: el });
    if (!generated) {
      for (const call of arr.elements) {
        if (call.type === 'CallExpression' && call.arguments[0]) {
          const itemId = staticString(call.arguments[0]);
          if (itemId) itemNodes.set(itemId, call);
        }
      }
    }
  }

  const baseSections = new Map(base.sections.map((s) => [s.id, s]));

  /* ---- reconcile each final section ---- */
  const finalSectionEls = [];
  for (const section of final.sections) {
    let node = sectionNodes.get(section.id);
    const baseSection = baseSections.get(section.id);
    const info = itemArrays.get(section.id);
    const itemsChanged = !baseSection || !deepEqual(baseSection.items, section.items);

    /* target item elements (only needed when items changed) */
    const buildItemEls = () => section.items.map((item) => {
      const existing = itemNodes.get(item.id);
      const flat = { ...item, sectionId: section.id };
      if (existing) {
        const patched = patchItemCall(existing, flat, section.id);
        if (patched) return patched;
      }
      return itemCallNode(flat);
    });

    if (!node) {
      // Brand-new section: inline items array (no separate const).
      node = sectionNode(section, b.arrayExpression(buildItemEls()));
    } else {
      // Patch scalar props that changed.
      if (!baseSection || baseSection.title !== section.title) setObjProp(node, 'title', section.title);
      if (!baseSection || baseSection.description !== section.description) setObjProp(node, 'description', section.description);
      if (!baseSection || baseSection.icon !== section.icon) setObjProp(node, 'icon', section.icon);
      if (!baseSection || baseSection.number !== section.number) setObjProp(node, 'number', section.number);
      if (!baseSection || baseSection.levelLabel !== section.levelLabel) {
        setObjProp(node, 'levelLabel', section.levelLabel || undefined);
      }
      if (itemsChanged) {
        if (info && info.arr) {
          info.arr.elements = buildItemEls();
        } else {
          // Generated section whose items were edited: materialize inline.
          const itemsProp = objProp(node, 'items');
          itemsProp.value = b.arrayExpression(buildItemEls());
        }
      }
    }
    finalSectionEls.push(node);
  }

  sectionsArr.elements = finalSectionEls;

  /* Removed sections whose `const sN = [...]` still exists: leave the const
   * (unreferenced but harmless) — deleting statements risks taking header
   * comments of neighbors with them. Validation reports unlisted consts. */

  return print(ast);
}
